version: "3.8"
services:
  app-front:
    image: app-front-app-front:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    volumes:
      - ./src:/app/src
